Accuchecker API
Karm/sinkit-core pull request #6
Opened 2018-07-04 13:20 UTC by hugeox

Updates blacklist cache and elastic with report sent to /blacklist/accuracyupdate/ from Accuchecker.
In terms of data validation this is taken care of by gson and using a new class IoCAccuCheckerReport which mimics the IoCRecord class but only allows fields source,accuracy and metadata. 

+ fix pushiocs.sh space bug

2018-08-27 12:30 UTC, hugeox commented on ejb/src/main/java/biz/karms/sinkit/ejb/impl/ArchiveServiceEJB.java
This should only accept IoCAccuCheckerReport to guarantee that hashes do not need to be recomputed.

2018-08-27 12:31 UTC, hugeox commented on ejb/src/main/java/biz/karms/sinkit/ejb/impl/ArchiveServiceEJB.java
> +    }
This should only accept IoCAccuCheckerReport to guarantee that hashes do not need to be recomputed.

2018-08-31 11:12 UTC, Karm requested changes
@hugeox 
 * attend to the notes from review please, especially to superfluous file etc.
 * also rebase so as the branch doesn't have conflicts
 * reopen against master, please
 * reword commits, e.g. "First steps" :-1:

2018-08-31 11:12 UTC, Karm commented on backp
> +    }
@hugeox This file was added by mistake apparently.

2018-08-31 11:12 UTC, Karm commented on ejb/src/main/java/biz/karms/sinkit/ejb/impl/ArchiveServiceEJB.java
> +        //assume less than 1000 results
@hugeox Could you elaborate more? 1000 results or what?

2018-08-31 11:12 UTC, Karm commented on ejb/src/main/java/biz/karms/sinkit/ejb/impl/CoreServiceEJB.java
> +        //returns true if all archivations and saves to cache succeed, otherwise returns false(or throws ArchiveException)
@hugeox Move to JavaDoc, please.

2018-08-31 11:12 UTC, Karm commented on ejb/src/main/java/biz/karms/sinkit/ejb/impl/CoreServiceEJB.java
> +        List<IoCRecord> iocs = archiveService.getMatchingEntries("source.id.value", source_id_value);
@hugeox The index is not used, fori would be better replaced with a lambda if you please.

2018-08-31 11:12 UTC, Karm commented on ejb/src/main/java/biz/karms/sinkit/ioc/IoCAccuCheckerReport.java
> +    //same structure as IoCRecord, but only allowing 3 fields.
@hugeox Move to JavaDoc, please.

2018-09-10 13:36 UTC, Karm approved these changes

2018-09-10 13:40 UTC, merged